title: Sarah Mostow
email: email@example.com
description: >
  Prospective PhD student in statistics interested in Empirical Bayes
  and multiple testing.
theme: jekyll-theme-cayman

markdown: kramdown
